### ISSUE TITLE
Cannot work in Riru v18

### ISSUE THREAD

**Issue by LiarOnce** [Kr328/Riru-InternalBrowserRedirect#1]

**Comment by Kr328** [comment]
@LiarOnce any log ?

**Comment by LiarOnce** [comment]
@Kr328
No, because I didn't get any logs.
![Screenshot_20190502-234705_Magisk_Manager.png](https://i.loli.net/2019/05/02/5ccb114822424.png)

**Comment by Kr328** [comment]
@LiarOnce 看起来 整个 Magisk 都爆炸了 (

**Comment by LiarOnce** [comment]
17.1的时候还能用，magisk也在18.1没升级过

**Comment by Kr328** [comment]
@LiarOnce Magisk 模块名 列表呢

**Comment by LiarOnce** [comment]
![Screenshot_20190503-004538_Magisk_Manager.png](https://i.loli.net/2019/05/03/5ccb1eceecb63.png)
![Screenshot_20190503-004532_Magisk_Manager.png](https://i.loli.net/2019/05/03/5ccb1ed3b3538.png)

**Comment by Kr328** [comment]
@LiarOnce 尝试重启后 抓取日志 https://bbs.mokeedev.com/t/topic/1236

**Comment by LiarOnce** [comment]
[logs.log](https://github.com/Kr328/Riru-InternalBrowserRedirect/files/3144014/logs.log)

**Comment by Kr328** [comment]
@LiarOnce 看起来 Riru 没有 尝试载入 InternalBrowserRedirect
尝试 再次刷入 InternalBrowserRedirect

**Comment by LiarOnce** [comment]
尝试过了，无效

**Comment by Kr328** [comment]
@LiarOnce 检查 以下文件 是否存在
  - /data/misc/riru/modules/ibr
  - /system/lib64/libriru_ibr.so

**Comment by LiarOnce** [comment]
存在

**Comment by Kr328** [comment]
@LiarOnce 等等 日志 貌似不是 重启 之后的 日志 (

**Comment by Kr328** [comment]
@Kr328 需要开机时的日志

**Comment by LiarOnce** [comment]
抓是抓到了，不过我照着edxp的module.prop抄了一份以后勉强恢复正常了。。。。。。 但触发跳转依然是概率性的（有时候成功有时候失败）
```
name=InternalBrowserRedirect
version=v5
versionCode=5
author=Kr328
description=Internal Browser Redirect
```

**Comment by Kr328** [comment]
尝试 https://github.com/Kr328/Riru-InternalBrowserRedirect/releases/tag/v6

**Comment by LiarOnce** [comment]
我暂时没有环境编译。。。。。。😂

**Comment by Kr328** [comment]
@LiarOnce 忘记上传 release 了 我的锅 (

**Comment by LiarOnce** [comment]
还是不行。。。。。。 
这是启动时的日志 [https://del.dog/uxahunarak](https://del.dog/uxahunarak)

**Comment by Kr328** [comment]
日志并不是从开机开始的 (Riru都没找到

**Comment by LiarOnce** [comment]
是开机时的日志啊，Riru的在第149行开始

**Comment by Kr328** [comment]
@LiarOnce 尝试删除 /data/misc/riru/modules/ibr 目录 重刷一遍 试试 (

**Comment by LiarOnce** [comment]
已解决
