### ISSUE TITLE
微信扫码时，部分第三方合作支付会跳转到外部浏览器导致无法支付。

### ISSUE THREAD

**Issue by Gokou-Ruri** [Kr328/Riru-InternalBrowserRedirect#11]
https://pijia.huiyinxun.com/aus-web/assets/html/web/error/noappscan.html
扫码后会调用外部浏览器，然后自动跳转到上方的链接。
好像是叫中银e信还是什么。

**Comment by Kr328** [comment]
@Gokou-Ruri 即将跳转时请选择 内部浏览器

**Comment by Gokou-Ruri** [comment]
@Kr328 没有选择菜单，扫码完直接就跳了。我的默认浏览器是Chrome v78。

**Comment by Kr328** [comment]
@Gokou-Ruri 模块版本 及 Riru 版本 是什么

**Comment by Gokou-Ruri** [comment]
riru 19.4，模块应该是v10吧。刚才更新了新版，明天再扫试试。
