### ISSUE TITLE
怎样实现不弹窗直接调用外部浏览器打开链接？

### ISSUE THREAD

**Issue by Gokou-Ruri** [Kr328/Riru-InternalBrowserRedirect#13]
尝试了“强制URL正则表达式”，发现没有效果。
在APP内置的QQ内置规则中已经存在了一条强制URL规则：
`(http|https):\//(.*weixin\.qq\.com)\/.*`
试着在QQ聊天框输入了一条“ https://1.weixin.qq.com/2 ”的链接，点击该链接还是会弹出窗口选择用QQ或Chrome打开。

**Comment by Kr328** [comment]
不能实现

**Comment by Kr328** [comment]
#12

**Comment by Gokou-Ruri** [comment]
@Kr328 感谢答复！<s>顺便请教一下目前版本这个“强制规则”的作用是什么？</s>
