### ISSUE TITLE
可否支持调用非系统默认浏览器？

### ISSUE THREAD

**Issue by Gokou-Ruri** [Kr328/Riru-InternalBrowserRedirect#18]
既然目前的版本无法实现全自动跳转外部浏览器，不如干脆支持非默认浏览器的调用？

建议请求理由：目前大多数用户的系统内都安装了多个“浏览器”，不同“浏览器”有不同功能，用来登录不同网站。
例如Via去广告非常好用而且支持外部下载器，用来打开一些小众向网站和需要下载文件的网页；Chrome同步Google数据可以记住密码所以登录常用的大网站；淘宝客户端则可以直接打开某些淘宝链接……等等。
目前Chrome是我的默认浏览器，但在QQ/微信里弹窗调用Chrome打开链接以后又要复制链接到其它“浏览器”的话，倒不如一开始就在QQ内复制过去更加方便。

**Comment by Kr328** [comment]
@Gokou-Ruri 本来就是列举出所有浏览器 

可能你的 ROM 比较弱智

不让 ACTION_VIEW 查询非系统默认浏览器

**Comment by Gokou-Ruri** [comment]
> @Gokou-Ruri 本来就是列举出所有浏览器
> 
> 可能你的 ROM 比较弱智
> 
> 不让 ACTION_VIEW 查询非系统默认浏览器

不知道`弱智`具体是指什么方面……我的ROM是`AOSiP 9.0-Official-20190704`。

**Comment by Kr328** [comment]
@Gokou-Ruri 是指 MIUI

ACTION_VIEW 只会也只能找到注册为浏览器的应用

如果应用没有注册 那么找到它们显示网页是完全不可能的

**Comment by Gokou-Ruri** [comment]
> @Gokou-Ruri 是指 MIUI
> 
> ACTION_VIEW 只会也只能找到注册为浏览器的应用
> 
> 如果应用没有注册 那么找到它们显示网页是完全不可能的

目前我在系统默认浏览器设置界面可以看到Chrome和IDM（一款下载器App），其它的因为被冻结了所以看不到。
不过IBR弹出的菜单里只有源App自身以及Chrome（我设置的默认浏览器）。

**Comment by Kr328** [comment]
@Gokou-Ruri 既然你是设置过默认浏览器 

ACTION_VIEW 确实只会查找到 这个浏览器

然而为了执行效率 也只能使用 ACTION_VIEW

**Comment by Gokou-Ruri** [comment]
> @Gokou-Ruri 既然你是设置过默认浏览器
> 
> ACTION_VIEW 确实只会查找到 这个浏览器
> 
> 然而为了执行效率 也只能使用 ACTION_VIEW

取消了默认浏览器，现在会弹出所有注册为浏览器的App了。但这样会在其它使用场景中造成很多不便（例如繁琐的操作步骤）。
可否增加备选方案呢？些许效率损失在我看来是可以接受的，又不是拖垮整个系统的量级。

**Comment by Kr328** [comment]
@Gokou-Ruri 很遗憾 确实会拖慢整个系统 会导致短时间内的 system_server 无响应

**Comment by Gokou-Ruri** [comment]
> @Gokou-Ruri 很遗憾 确实会拖慢整个系统 会导致短时间内的 system_server 无响应

好吧，谢谢解答。
