### ISSUE TITLE
支持对对已获取的 url 的清洗

### ISSUE THREAD

**Issue by RanKKI** [Kr328/Riru-InternalBrowserRedirect#19]
能不能加一个 feature

比如 abc.com/?redirect=www.123.abc

可以通过正则获取 www.123.abc，然后打开。

**Comment by Kr328** [comment]
@RanKKI 不需要正则 现有版本已经包含 Uri 参数解析 在结尾加上 /redirect 即可

**Comment by RanKKI** [comment]
> @RanKKI 不需要正则 现有版本已经包含 Uri 参数解析 在结尾加上 /redirect 即可

好的， 因为没有在项目里看到关于 redirect 相关的描述，
感谢～

**Comment by Kr328** [comment]
@RanKKI 因为是测试特性

另外这个只是从 Uri 里 取参数 不会去真正的 访问网站

除了 redirect 外 其他参数同样是支持的 (例如 知乎 的 url
