### ISSUE TITLE
QQ邮箱

### ISSUE THREAD

**Issue by Vstory** [Kr328/Riru-InternalBrowserRedirect#3]
config.com.tencent.androidqqmail.json

`{
	"name": "QQMail",
	"rules": [
		{
			"extra-key": "url",
			"ignore-url": ".*qq\\.com.*",
			"force-url": ""
		}
	]
} `

**Comment by Kr328** [comment]
New rule repo on [here](https://github.com/Kr328/Riru-InternalBrowserRedirect-Rules)
