### ISSUE TITLE
安卓Q无效

### ISSUE THREAD

**Issue by SDchao** [Kr328/Riru-InternalBrowserRedirect#5]
日志中没有相关TAG
Riru-Core和该模块版本都是最新的
so文件和配置文件夹均有正常创建

**Comment by Kr328** [comment]
@SDchao 因为 我没有 能够使用 Q的设备 这个得等很久才能修

**Comment by SDchao** [comment]
> @SDchao 因为 我没有 能够使用 Q的设备 这个得等很久才能修

好的，辛苦啦~

**Comment by Kr328** [comment]
已在 v11 支持
