### ISSUE TITLE
知乎要怎么设置

### ISSUE THREAD

**Issue by togls** [Kr328/Riru-InternalBrowserRedirect#6]
{
	"name": "zhihu",
	"rules": [
		{
			"extra-key": "url",
			"ignore-url": ".*zhihu\\.com.*",
			"force-url": ".*link\\.zhihu\\.com.*"
		}
	]
} 
这样子不行

**Comment by Kr328** [comment]
@tongls logcat please

**Comment by togls** [comment]
@Kr328 

`06-16 19:29:59.109  2613  2613 I InternalBrowserRedirect: Inject com.zhihu.android
06-16 19:29:59.179  8640  8640 I InternalBrowserRedirect: Injecting
06-16 19:29:59.179  8640  8640 I InternalBrowserRedirect: Inject zhihu Success
06-16 19:30:02.686  8640  8640 D InternalBrowserRedirect: matching .*zhihu\.com.* .*link\.zhihu\.com.*
06-16 19:30:02.686  8640  8640 I InternalBrowserRedirect: zhihu: Ignore intent Intent { cmp=com.zhihu.android/.app.ui.activity.MainActivity }null
06-16 19:30:09.728  2613  2613 I InternalBrowserRedirect: Inject com.zhihu.android
06-16 19:30:09.795  9077  9077 I InternalBrowserRedirect: Injecting
06-16 19:30:09.795  9077  9077 I InternalBrowserRedirect: Inject zhihu Success
06-16 19:30:35.448  8640  8640 D InternalBrowserRedirect: matching .*zhihu\.com.* .*link\.zhihu\.com.*
06-16 19:30:35.448  8640  8640 I InternalBrowserRedirect: zhihu: Ignore intent Intent { cmp=com.zhihu.android/.app.ui.activity.HostActivity (has extras) }Bundle[{intent_extra_zhintent=com.zhihu.android.app.util.ZHIntent@c72e208}]
06-16 19:31:17.830  8640  8640 D InternalBrowserRedirect: matching .*zhihu\.com.* .*link\.zhihu\.com.*
06-16 19:31:17.830  8640  8640 I InternalBrowserRedirect: zhihu: Modified intent Intent { act=android.intent.action.VIEW dat=https://link.zhihu.com/... flg=0x10000000 (has extras) }Bundle[{android.support.customtabs.extra.SESSION=null, android.support.customtabs.extra.TITLE_VISIBILITY=1, android.support.customtabs.extra.TOOLBAR_COLOR=-16743169, android.support.customtabs.extra.EXTRA_ENABLE_INSTANT_APPS=true}]`

**Comment by Kr328** [comment]
这个已经是在外部浏览器打开了
是 Chrome 的 Custom Tabs
[参见](https://juejin.im/entry/586f089c61ff4b006d29f9c0)
