### ISSUE TITLE
关于点击链接后的弹窗提示的疑问

### ISSUE THREAD

**Issue by cxyzzz** [Kr328/Riru-InternalBrowserRedirect#9]
![Screenshot_2019-08-09-22-26-40-903_android](https://user-images.githubusercontent.com/21036341/62786278-d92e7d80-baf4-11e9-96b7-7177cb0b8a86.png)
启用的规则是自带的，点击链接时提示选择哪个浏览器打开，我个人理解是选择内部浏览器是使用软件本身打开选择其它的才是使用外部浏览器打开，但实际情况是选择Chrome才是使用软件内部浏览器打开，选择内部浏览器反而是使用Chrome打开。不清楚是不是系统原因。ps:我禁用了X5内核，系统WebView是AndroidWebView

**Comment by Kr328** [comment]
@cxyzzz 这个似乎是你的系统的行为
我这里无法复现
